//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class etudiant
    {
        public int id_etudiant { get; set; }
        public string nom_etudiant { get; set; }
        public Nullable<int> id_filiere { get; set; }
    
        public virtual filiere filiere { get; set; }
    }
}
